version: '3.5'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    depends_on:
      - mysql-server
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_password"
      MYSQL_ROOT_PASSWORD: "root_password"
      PHP_TZ: "UTC"
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"

  zabbix-agent:
    build:
      context: .
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-server

  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
